build_image:
  image: node:12-alpine
  stage: build
  script:
    - npm link @angular/cli@11.2.6
    - cd /builds/nunow/Legance-Irina-Frontend/fe-workspace
    - npm install
    - ng build fe-common --prod
    - ng build fe-app --prod --base-href /  --output-hashing=all;
    - ng build fe-insights --prod  --base-href / --output-hashing=all;
    - ng build fe-touchpoint --prod --base-href / --output-hashing=all;
  artifacts:
    paths:
      - $CI_PROJECT_DIR/dist
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules
    policy: pull
